## ID : 816000325
## Name: Ajay Sieunarine
## Email: ajay.sieunarine@my.uwi.edu
## Repo: https://github.com/jefroy/big-data-A4

In [1]:
# math and graph stuff
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# text analysis stuff
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
import string
from nltk import ngrams
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer
from string import punctuation

# ML stuff
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score, f1_score
from sklearn import svm
from sklearn.decomposition import NMF, LatentDirichletAllocation, TruncatedSVD

# utility stuff
from sklearn.utils import shuffle
from itertools import chain
from sklearn.preprocessing import LabelEncoder


sep = '============================================================================================'

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\idisc\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\idisc\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


# Warm Up (20 marks) 

In [2]:
# documents/sentences
corpus = [ 
    'Apple Orange Orange Apple',
    'Apple Banana Apple Banana',
    'Banana Apple Banana Banana Banana Apple',
    'Banana Orange Banana Banana Orange Banana',
    'Banana Apple Banana Banana Orange Banana'
]

def corp2vec(corpus):
    '''
    This function converts a document to a vector showing its term frequencies.
    Each column represents a term in the corpus. (in this case, there are 3 terms).
    Uses CountVectorizer() as a model.
    '''
    tf_vectorizer = CountVectorizer() # model
    tf = tf_vectorizer.fit_transform(corpus) # get term frequencies
    return tf.A # return the array representation

print(type(corp2vec(corpus)))
print(corp2vec(corpus))

<class 'numpy.ndarray'>
[[2 0 2]
 [2 2 0]
 [2 4 0]
 [0 4 2]
 [1 4 1]]


# Preprocessing and Data Organization (20 marks) 

In [3]:
df = pd.read_csv('MrTrumpSpeeches.csv', sep='~', encoding="ISO-8859-1")
df.head()

id                        playlist  upload_date  \
0  -2WTNSujhjk  Donald Trump Speeches & Events     20160220   
1  -64nfy6i58w  Donald Trump Speeches & Events     20161107   
2  -7Sp31hTxkU  Donald Trump Speeches & Events     20160423   
3  -byuyavcNI4  Donald Trump Speeches & Events     20160617   
4  09BXh-AA72M  Donald Trump Speeches & Events     20161105   

                                               title  view_count  \
0  Live Stream: Donald Trump Victory Rally in Spa...      4057.0   
1  LAST RALLY: Donald Trump FINAL CAMPAIGN Rally ...     47276.0   
2  FULL SPEECH: Donald Trump Rally in Bridgeport,...     19966.0   
3  Full Speech: Donald Trump Rally in Houston, Te...     15138.0   
4  Full Speech: Donald Trump Rally in Denver, Col...      8720.0   

   average_rating  like_count  dislike_count  \
0        4.259259        44.0           10.0   
1        4.358025       952.0          182.0   
2        4.666667       220.0           20.0   
3        4.582491       266.0           31.0   
4        4.924731       365.0            7.0   

                                           subtitles  
0     presidents of the United States mr. go   tr...  
1     it's now officially Tuesday November a   di...  
2     you   [Music]   [Music]   [Music]   you   I...  
3     we welcome stars and president   [Music]   ...  
4     you   thank you   [Music]   great people Gr...

In [4]:
df.dtypes

id                 object
playlist           object
upload_date         int64
title              object
view_count        float64
average_rating    float64
like_count        float64
dislike_count     float64
subtitles          object
dtype: object

## Task 1: 
Create a new column in the dataframe called 'sentiment'. Using appropriate existing columns, populate the new column with 0's and 1's where 0 refers to a negative sentiment and 1 refers to a positive sentiment. 

- using the `average_rating` column, find the average score
    * ratings above or equal to this average are denoted by sentiment = 1
    * ratings under this average are denoted by sentiment = 0

In [5]:
# find the avg/mid score possible:
max_score = max(df['average_rating'])
min_score = min(df['average_rating'])
avg_score = (max_score + min_score) / 2
print(max_score)
print(min_score)
print(avg_score)

5.0
1.34782612324
3.17391306162


In [6]:
def pruneRating(x):
    '''
    utility function for lambda
    returns 1 for good/avg rating
    returns 0 for bad rating
    '''
    if x >= avg_score:
        return 1
    if x < avg_score:
        return 0

df['sentiment'] = df['average_rating'].apply(
    lambda x: pruneRating(x)
)

enc3 = LabelEncoder()
enc3.fit(df['sentiment'])

print(enc3.classes_)
print(sep)
print(df['sentiment'].describe()) 
print(sep)
df.head()

[0 1]
count    836.000000
mean       0.903110
std        0.295985
min        0.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        1.000000
Name: sentiment, dtype: float64


id                        playlist  upload_date  \
0  -2WTNSujhjk  Donald Trump Speeches & Events     20160220   
1  -64nfy6i58w  Donald Trump Speeches & Events     20161107   
2  -7Sp31hTxkU  Donald Trump Speeches & Events     20160423   
3  -byuyavcNI4  Donald Trump Speeches & Events     20160617   
4  09BXh-AA72M  Donald Trump Speeches & Events     20161105   

                                               title  view_count  \
0  Live Stream: Donald Trump Victory Rally in Spa...      4057.0   
1  LAST RALLY: Donald Trump FINAL CAMPAIGN Rally ...     47276.0   
2  FULL SPEECH: Donald Trump Rally in Bridgeport,...     19966.0   
3  Full Speech: Donald Trump Rally in Houston, Te...     15138.0   
4  Full Speech: Donald Trump Rally in Denver, Col...      8720.0   

   average_rating  like_count  dislike_count  \
0        4.259259        44.0           10.0   
1        4.358025       952.0          182.0   
2        4.666667       220.0           20.0   
3        4.582491       266.0           31.0   
4        4.924731       365.0            7.0   

                                           subtitles  sentiment  
0     presidents of the United States mr. go   tr...          1  
1     it's now officially Tuesday November a   di...          1  
2     you   [Music]   [Music]   [Music]   you   I...          1  
3     we welcome stars and president   [Music]   ...          1  
4     you   thank you   [Music]   great people Gr...          1

## Task 2
- Clean the subtitles data and store the cleaned text in a new column 'subtitle_clean'.
    * For each step of your text cleaning give a brief explanation of why you chose to perform that method on the text. 
        1. Removing additional white spaces
        2. Replacing emoji's with a word representation for example :) ==> smile
        3. Removing links from the corpus
        4. Removing punctuation
        5. Removing HTML tags
        6. Remove duplicate reviews

In [7]:
# this block of code will take a little while to process since the text is being thoroughly cleaned.
def text_process(mess):
    """
    Takes in a string of text, then performs the following:
    1. Remove all punctuation
    2. Remove all stopwords
    3. Returns a list of the cleaned text
    """
    # Check characters to see if they are in punctuation
    nopunc = [char for char in mess if char not in string.punctuation]

    # Join the characters again to form the string.
    nopunc = ''.join(nopunc)
    
    # Now just remove any stopwords
    words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    
    # convert all words to lowercase and lemmatize and stem
    wnl = WordNetLemmatizer()
    porter = PorterStemmer()
    arr = []
    for word in words:
        word = word.lower()
        word = porter.stem(word)
        word = wnl.lemmatize(word)
        arr.append(word)

    return arr

def test_text_process():
    '''
    function to hold some test cases to ensure the lambda function does its job
    '''
    print(
        'Test stopwords and lowercase:\nHI I AM A STOPWORD = ', 
        text_process("HI I AM A STOPWORD")
    )
    print(sep)
    print(
        'Test Stemming words and removing punctuation:\nfishing, fisher, fished = ', 
        text_process("fishing, fisher , fished")
    )

def pruneSubtitle(x):
    '''
    utility function for lambda
    x - string from `subtitles` col
    '''
    return text_process(x)

# test_text_process()

df['subtitle_clean'] = df['subtitles'].apply(
    lambda x: pruneSubtitle(x)
)

df.head()

id                        playlist  upload_date  \
0  -2WTNSujhjk  Donald Trump Speeches & Events     20160220   
1  -64nfy6i58w  Donald Trump Speeches & Events     20161107   
2  -7Sp31hTxkU  Donald Trump Speeches & Events     20160423   
3  -byuyavcNI4  Donald Trump Speeches & Events     20160617   
4  09BXh-AA72M  Donald Trump Speeches & Events     20161105   

                                               title  view_count  \
0  Live Stream: Donald Trump Victory Rally in Spa...      4057.0   
1  LAST RALLY: Donald Trump FINAL CAMPAIGN Rally ...     47276.0   
2  FULL SPEECH: Donald Trump Rally in Bridgeport,...     19966.0   
3  Full Speech: Donald Trump Rally in Houston, Te...     15138.0   
4  Full Speech: Donald Trump Rally in Denver, Col...      8720.0   

   average_rating  like_count  dislike_count  \
0        4.259259        44.0           10.0   
1        4.358025       952.0          182.0   
2        4.666667       220.0           20.0   
3        4.582491       266.0           31.0   
4        4.924731       365.0            7.0   

                                           subtitles  sentiment  \
0     presidents of the United States mr. go   tr...          1   
1     it's now officially Tuesday November a   di...          1   
2     you   [Music]   [Music]   [Music]   you   I...          1   
3     we welcome stars and president   [Music]   ...          1   
4     you   thank you   [Music]   great people Gr...          1   

                                      subtitle_clean  
0  [presid, unit, state, mr, go, trapp, famili, t...  
1  [offici, tuesday, novemb, ever, think, youd, h...  
2  [music, music, music, great, countri, leader, ...  
3  [welcom, star, presid, music, place, live, pla...  
4  [thank, music, great, peopl, granna, three, da...